### ISSUE TITLE
Updates to /plans-and-pricing page (from C Johnston)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3306] opened 2018-06-12 12:50 UTC
As per copydoc: https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#

**Comment by frankiegranato** [comment] 2018-06-12 12:51
If the comments in the doc look unresolved, please talked to me before completing this work @steverydz

**Comment by shivjoshi1996** [comment] 2018-06-27 14:44
Dupe of https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/3437

**Closed by shivjoshi1996** 2018-06-27 14:44 UTC
Labels: Duplicate
