### ISSUE TITLE
Ubuntu 16.04 LTS download link is broken (both 32bit and 64bit)

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2138] opened 2017-08-14 14:21 UTC
## Summary

http://cn.ubuntu.com/download/

Download links for 63 and 32 are broken. 
## Process

Visit: http://cn.ubuntu.com/download/
Click button to download Ubuntu 16.04 LTS 64 and 32

## Current and expected result

http://cn.ubuntu.com/download/
Currently ubuntu-16.04.2-desktop-amd64.iso
please replace with ubuntu-16.04.3-desktop-amd64.iso

**Comment by pmahnke** [comment] 2017-08-14 14:32
duplicate of https://github.com/canonical-websites/cn.ubuntu.com/issues/144, closing

**Closed by pmahnke** 2017-08-14 14:32 UTC
Labels: Type: Bug
