### ISSUE TITLE
Create the /download/core/raspberry-pi-compute-module-3 page

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#2682] opened 2018-02-11 08:29 UTC
Create the www.ubuntu.com/download/core/raspberry-pi-compute-module-3 page

**Comment by pmahnke** [comment] 2018-02-11 08:30
### /download/core/raspberry-pi-compute-module-3

[copy doc for the Raspberry Pi Compute Module 3](https://docs.google.com/document/d/1BO8UI7BNDbyLhLcRSbxzhhaAj-dO6AbYPJUJ0A36vCQ/edit#heading=h.mc3o8aqq492k) and the [original developer.u.c page](https://developer.ubuntu.com/core/get-started/compute-module-3)

**Comment by Caleb-Ellis** [comment] 2018-02-13 09:16
Duplicate of #2669

**Closed by Caleb-Ellis** 2018-02-13 09:16 UTC
