### ISSUE TITLE
Mis-counted search results

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/www.ubuntu.com#2628] opened 2018-02-05 14:07 UTC
## Summary

When searching ubuntu.com, the results page miscounts the number of hits.

## Process

1. Go to https://www.ubuntu.com/
2. Search for something e.g. linux
3. Look at the results page, e.g. https://www.ubuntu.com/search?q=linux

## Current and expected result

Currently the page shows 0 hits, and isn't counting the results properly "Results to of 0"

I expect it to tell me how many hits there were and to indicate which "page" of the results I'm viewing.
 
## Screenshot

![Screenshot](https://user-images.githubusercontent.com/246192/35808453-ba6c6b06-0a7d-11e8-862e-ad6a77f836ce.png)

**Comment by sparkiegeek** [comment] 2018-02-05 14:07
See also https://github.com/canonical-websites/docs.ubuntu.com/issues/136

**Comment by matthewpaulthomas** [comment] 2018-02-15 14:44
Duplicate of #2570.

**Closed by matthewpaulthomas** 2018-02-15 14:44 UTC
