### ISSUE TITLE
Partner's logo fail to load

### ISSUE THREAD

**Issue by Vickiv** [canonical-websites/www.ubuntu.com#3778] opened 2018-07-23 08:47 UTC
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Partner's logo fail to load

## Process

Open https://www.ubuntu.com/server

## Screenshot

![capture](https://user-images.githubusercontent.com/33767405/43066730-b520b672-8e65-11e8-811a-40465a2807f6.PNG)

**Comment by steverydz** [comment] 2018-07-23 08:51
Thanks for filing an issue. We hope to have a fix for this soon.

**Comment by nottrobin** [comment] 2018-08-02 11:59
This was caused by the HTTPS certificate for partners.ubuntu.com not appearing valid from command-line tools - importantly here, not appearing valid to the Python app that runs www.ubuntu.com.

``` bash
$ wget https://partners.ubuntu.com
--2018-08-02 12:25:03--  https://partners.ubuntu.com/
Resolving partners.ubuntu.com (partners.ubuntu.com)... 162.213.33.151
Connecting to partners.ubuntu.com (partners.ubuntu.com)|162.213.33.151|:443=
... connected.
ERROR: cannot verify partners.ubuntu.com's certificate, issued by =E2=80=98=
CN=3DDigiCert SHA2 Secure Server CA,O=3DDigiCert Inc,C=3DUS=E2=80=99:
  Unable to locally verify the issuer's authority.
To connect to partners.ubuntu.com insecurely, use `--no-check-certificate'.
```

The error from the application was:

```
'[Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFIC=
ATE:certificate verify failed'
```

The certificate and the error should now be fixed.

**Closed by nottrobin** 2018-08-02 11:59 UTC
Labels: Priority: Medium, Type: Bug
