### ISSUE TITLE
Description of private cloud requirements is incorrect

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/www.ubuntu.com#2566] opened 2018-01-05 18:01 UTC
This page is slightly incorrect and we should replace the following sentence:
**Build your own production cloud**
OpenStack with conjure-up
Thanks to MAAS, the bare metal provisioning and management tool, conjure-up can talk to a cluster of servers.
Requirements
4 x Intel x64 servers each with:
8GB RAM
Management card/BMC with IPMI onboard

Replace by:

**Build your own private cloud**
OpenStack with conjure-up
Thanks to MAAS, the bare metal provisioning and management tool, conjure-up can talk to a cluster of servers.
Minimum requirements
4 x Intel x64 servers each with:
8GB RAM
Management card/BMC with IPMI onboard

_For production clouds 12 nodes are required, including 3 nodes for High Availability MAAS-based infrastructure_

Delta summary

    - Replace "Production" by "Private"

    - Change "Requirements" to "Minimum Requirements"

    - Note in fine print "For production clouds 12 nodes are required,
      including 3 nodes for High Availability MAAS-based infrastructure"

Thanks,
---
*Reported from: https://www.ubuntu.com/download/cloud/build-openstack*

**Comment by pmahnke** [comment] 2018-01-07 16:24
Closing - duplicate of #2554 and fixed by #2559... and FYI, if you look in the copy doc, I didn't do 'Build your own private cloud' but 'Build your own production private cloud' as it is referenced by /download/cloud as a production cloud.

**Closed by pmahnke** 2018-01-07 16:24 UTC
Labels: Duplicate
