### ISSUE TITLE
Update /openstack/install page instructions

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4275] opened 2018-10-23 21:22 UTC
per the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#heading=h.c4pfpz5v1oh0)

**Comment by shivjoshi1996** [comment] 2018-10-31 10:39
This is a dupe of https://github.com/canonical-websites/www.ubuntu.com/issues/4294

**Closed by shivjoshi1996** 2018-10-31 10:39 UTC
Labels: Priority: Medium
